name: Docs
on: [push, pull_request]
jobs:
  build-docs:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Hatch
        uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc
      - run: hatch run docs:build
      - run: touch docs/_build/html/.nojekyll
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: htmldocs
          path: docs/_build/html
  deploy-docs:
    name: Deploy
    needs: build-docs
    if: "github.event_name == 'push' && github.ref == 'refs/heads/master'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: htmldocs
          path: html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: html
          clean: true
          force: true
