name: Docs
on: [push, pull_request]
jobs:
  build-docs:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: x64
      - run: pip install -e ".[docs]"
      - run: sphinx-build -a docs/ docs/_build/html
      - run: touch docs/_build/html/.nojekyll
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: htmldocs
          path: docs/_build/html
  deploy-docs:
    name: Deploy
    needs: build-docs
    if: "github.event_name == 'push' && github.ref == 'refs/heads/master'"
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: htmldocs
          path: html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: html
