name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: "${{ matrix.tool.name }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool:
          - name: black
            invocation: black --check --diff .
          - name: flake8
            invocation: flake8 .
          - name: isort
            invocation: isort --check --diff .
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: x64
      - run: "pip install ${{ matrix.tool.name }}"
      - run: "${{ matrix.tool.invocation }}"
